# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='price',
            name='to_date',
        ),
    ]
