# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20180310_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
