# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20180310_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
